import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
from pathlib import Path
import numpy as np


def read_data(filename: str):
    path = Path(filename)

    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {filename}\n"
            f"Expected it to be generated by your C++ finalize_solution()."
        )

    df = pd.read_csv(path)

    if "Time" not in df.columns or "Value" not in df.columns:
        raise ValueError(
            f"{filename} must have columns: Time, Value. "
            f"Got: {list(df.columns)}"
        )

    return df["Time"].to_numpy(), df["Value"].to_numpy()


# ============================================================
# Obstacle settings
# Must match the obstacle values hardcoded in your C++ OPP.
# ============================================================

OBSTACLES = [
    (-0.6, 2.0),
    (0.6, 1.8),
]

OBSTACLE_RADIUS = 0.30


# ============================================================
# Load REAL-time trajectories + control points
# ============================================================

times_px, values_px = read_data("px_real.csv")
cp_times_px, cp_values_px = read_data("px_controlpoints_real.csv")

times_py, values_py = read_data("py_real.csv")
cp_times_py, cp_values_py = read_data("py_controlpoints_real.csv")

times_pz, values_pz = read_data("pz_real.csv")
cp_times_pz, cp_values_pz = read_data("pz_controlpoints_real.csv")

times_psi, values_psi = read_data("psi_real.csv")
cp_times_psi, cp_values_psi = read_data("psi_controlpoints_real.csv")

times_vx, values_vx = read_data("vx_real.csv")
cp_times_vx, cp_values_vx = read_data("vx_controlpoints_real.csv")

times_vy, values_vy = read_data("vy_real.csv")
cp_times_vy, cp_values_vy = read_data("vy_controlpoints_real.csv")

times_vz, values_vz = read_data("vz_real.csv")
cp_times_vz, cp_values_vz = read_data("vz_controlpoints_real.csv")

times_w, values_w = read_data("w_real.csv")
cp_times_w, cp_values_w = read_data("w_controlpoints_real.csv")

times_ax, values_ax = read_data("ax_real.csv")
cp_times_ax, cp_values_ax = read_data("ax_controlpoints_real.csv")

times_ay, values_ay = read_data("ay_real.csv")
cp_times_ay, cp_values_ay = read_data("ay_controlpoints_real.csv")

times_az, values_az = read_data("az_real.csv")
cp_times_az, cp_values_az = read_data("az_controlpoints_real.csv")

times_aw, values_aw = read_data("aw_real.csv")
cp_times_aw, cp_values_aw = read_data("aw_controlpoints_real.csv")


# ============================================================
# Print XY control points
# ============================================================

print("\n============================================================")
print("XY CONTROL POINTS")
print("============================================================")

for i, (x_cp, y_cp) in enumerate(zip(cp_values_px, cp_values_py)):
    print(f"CP {i:02d}: px = {x_cp: .9f}, py = {y_cp: .9f}")

print("============================================================\n")


# ============================================================
# Print obstacle distance check from sampled Bernstein trajectory
# ============================================================

print("============================================================")
print("OBSTACLE DISTANCE CHECK FROM SAMPLED BERNSTEIN TRAJECTORY")
print("============================================================")

for idx, (ox, oy) in enumerate(OBSTACLES, start=1):
    distances = np.sqrt((values_px - ox) ** 2 + (values_py - oy) ** 2)
    min_distance = np.min(distances)
    min_index = np.argmin(distances)

    print(
        f"Obstacle {idx}: "
        f"center = ({ox:.6f}, {oy:.6f}), "
        f"radius = {OBSTACLE_RADIUS:.6f}, "
        f"sampled min distance = {min_distance:.9f}, "
        f"closest sample index = {min_index}, "
        f"closest point = ({values_px[min_index]:.9f}, {values_py[min_index]:.9f})"
    )

print("============================================================\n")


# ============================================================
# Plot settings
# ============================================================

line_width = 0.8
cp_size = 60


# ============================================================
# Plot 1: positions px, py, pz, psi versus time
# ============================================================

plt.figure(figsize=(10, 6))

plt.plot(
    times_px,
    values_px,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="px",
)

plt.plot(
    times_py,
    values_py,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="py",
)

plt.plot(
    times_pz,
    values_pz,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="pz",
)

plt.plot(
    times_psi,
    values_psi,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="psi",
)

plt.scatter(
    cp_times_px,
    cp_values_px,
    s=cp_size,
    label="px control points",
)

plt.scatter(
    cp_times_py,
    cp_values_py,
    s=cp_size,
    label="py control points",
)

plt.scatter(
    cp_times_pz,
    cp_values_pz,
    s=cp_size,
    label="pz control points",
)

plt.scatter(
    cp_times_psi,
    cp_values_psi,
    s=cp_size,
    label="psi control points",
)

plt.title("BeBOT states: px, py, pz, psi")
plt.xlabel("Time [s]")
plt.ylabel("Value")
plt.grid(True)
plt.legend()
plt.tight_layout()


# ============================================================
# Plot 2: velocities vx, vy, vz, w versus time
# ============================================================

plt.figure(figsize=(10, 6))

plt.plot(
    times_vx,
    values_vx,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="vx",
)

plt.plot(
    times_vy,
    values_vy,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="vy",
)

plt.plot(
    times_vz,
    values_vz,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="vz",
)

plt.plot(
    times_w,
    values_w,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="w",
)

plt.scatter(
    cp_times_vx,
    cp_values_vx,
    s=cp_size,
    label="vx control points",
)

plt.scatter(
    cp_times_vy,
    cp_values_vy,
    s=cp_size,
    label="vy control points",
)

plt.scatter(
    cp_times_vz,
    cp_values_vz,
    s=cp_size,
    label="vz control points",
)

plt.scatter(
    cp_times_w,
    cp_values_w,
    s=cp_size,
    label="w control points",
)

plt.title("BeBOT states: vx, vy, vz, w")
plt.xlabel("Time [s]")
plt.ylabel("Value")
plt.grid(True)
plt.legend()
plt.tight_layout()


# ============================================================
# Plot 3: controls ax, ay, az, aw versus time
# ============================================================

plt.figure(figsize=(10, 6))

plt.plot(
    times_ax,
    values_ax,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="ax",
)

plt.plot(
    times_ay,
    values_ay,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="ay",
)

plt.plot(
    times_az,
    values_az,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="az",
)

plt.plot(
    times_aw,
    values_aw,
    marker=".",
    linestyle=":",
    linewidth=line_width,
    label="aw",
)

plt.scatter(
    cp_times_ax,
    cp_values_ax,
    s=cp_size,
    label="ax control points",
)

plt.scatter(
    cp_times_ay,
    cp_values_ay,
    s=cp_size,
    label="ay control points",
)

plt.scatter(
    cp_times_az,
    cp_values_az,
    s=cp_size,
    label="az control points",
)

plt.scatter(
    cp_times_aw,
    cp_values_aw,
    s=cp_size,
    label="aw control points",
)

plt.title("BeBOT controls: ax, ay, az, aw")
plt.xlabel("Time [s]")
plt.ylabel("Value")
plt.grid(True)
plt.legend()
plt.tight_layout()


# ============================================================
# Plot 4: XY obstacle avoidance path with printed control points
# ============================================================

plt.figure(figsize=(9, 8))
ax = plt.gca()

# Smooth Bernstein trajectory in XY
plt.plot(
    values_px,
    values_py,
    linewidth=2.0,
    label="Bernstein trajectory",
)

# XY control polygon
plt.plot(
    cp_values_px,
    cp_values_py,
    "o--",
    linewidth=1.2,
    markersize=6,
    label="Control polygon",
)

# Annotate every XY control point
for i, (x_cp, y_cp) in enumerate(zip(cp_values_px, cp_values_py)):
    ax.annotate(
        f"CP{i}\n({x_cp:.2f}, {y_cp:.2f})",
        xy=(x_cp, y_cp),
        xytext=(8, 8),
        textcoords="offset points",
        fontsize=8,
        bbox=dict(
            boxstyle="round,pad=0.2",
            fc="white",
            alpha=0.75,
        ),
        arrowprops=dict(
            arrowstyle="->",
            linewidth=0.6,
        ),
    )

# Start point from sampled trajectory
plt.scatter(
    values_px[0],
    values_py[0],
    s=120,
    marker="s",
    label="Start sampled point",
)

# Final sampled point
plt.scatter(
    values_px[-1],
    values_py[-1],
    s=140,
    marker="*",
    label="Final sampled point",
)

# First control point
plt.scatter(
    cp_values_px[0],
    cp_values_py[0],
    s=90,
    marker="x",
    linewidths=2,
    label="First control point",
)

# Last control point
plt.scatter(
    cp_values_px[-1],
    cp_values_py[-1],
    s=90,
    marker="P",
    label="Last control point",
)

# Obstacles
for idx, (ox, oy) in enumerate(OBSTACLES, start=1):
    circle = Circle(
        (ox, oy),
        OBSTACLE_RADIUS,
        fill=True,
        alpha=0.35,
        edgecolor="black",
        linewidth=1.5,
        label=f"Obstacle {idx}",
    )

    ax.add_patch(circle)

    plt.scatter(
        ox,
        oy,
        marker="x",
        s=80,
        linewidths=2,
        color="black",
    )

    ax.annotate(
        f"Obs {idx}\n({ox:.2f}, {oy:.2f})",
        xy=(ox, oy),
        xytext=(10, -20),
        textcoords="offset points",
        fontsize=8,
        bbox=dict(
            boxstyle="round,pad=0.2",
            fc="white",
            alpha=0.75,
        ),
    )

# Axis limits
all_x = (
    list(values_px)
    + list(cp_values_px)
    + [obs[0] - OBSTACLE_RADIUS for obs in OBSTACLES]
    + [obs[0] + OBSTACLE_RADIUS for obs in OBSTACLES]
)

all_y = (
    list(values_py)
    + list(cp_values_py)
    + [obs[1] - OBSTACLE_RADIUS for obs in OBSTACLES]
    + [obs[1] + OBSTACLE_RADIUS for obs in OBSTACLES]
)

margin = 0.5

plt.xlim(min(all_x) - margin, max(all_x) + margin)
plt.ylim(min(all_y) - margin, max(all_y) + margin)

plt.title("XY Obstacle Avoidance with Control Points")
plt.xlabel("px [m]")
plt.ylabel("py [m]")
plt.axis("equal")
plt.grid(True)
plt.legend(loc="best")
plt.tight_layout()


plt.show()
