import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path


def read_data(filename: str):
    path = Path(filename)
    if not path.exists():
        raise FileNotFoundError(
            f"Missing file: {filename}\n"
            f"Expected it to be generated by your C++ finalize_solution()."
        )
    df = pd.read_csv(path)
    if "Time" not in df.columns or "Value" not in df.columns:
        raise ValueError(f"{filename} must have columns: Time, Value. Got: {list(df.columns)}")
    return df["Time"].to_numpy(), df["Value"].to_numpy()


# ---------- Load REAL-time trajectories + control points ----------
times_z, values_z = read_data("z_real.csv")
cp_times_z, cp_values_z = read_data("z_controlpoints_real.csv")

times_theta, values_theta = read_data("theta_real.csv")
cp_times_theta, cp_values_theta = read_data("theta_controlpoints_real.csv")

times_w, values_w = read_data("w_real.csv")
cp_times_w, cp_values_w = read_data("w_controlpoints_real.csv")

times_q, values_q = read_data("q_real.csv")
cp_times_q, cp_values_q = read_data("q_controlpoints_real.csv")

times_psi, values_psi = read_data("psi_real.csv")
cp_times_psi, cp_values_psi = read_data("psi_controlpoints_real.csv")

times_r, values_r = read_data("r_real.csv")
cp_times_r, cp_values_r = read_data("r_controlpoints_real.csv")

times_dv, values_dv = read_data("delta_v_real.csv")
cp_times_dv, cp_values_dv = read_data("delta_v_controlpoints_real.csv")

times_dm, values_dm = read_data("delta_m_real.csv")
cp_times_dm, cp_values_dm = read_data("delta_m_controlpoints_real.csv")

times_ds, values_ds = read_data("delta_s_real.csv")
cp_times_ds, cp_values_ds = read_data("delta_s_controlpoints_real.csv")

times_dh, values_dh = read_data("delta_h_real.csv")
cp_times_dh, cp_values_dh = read_data("delta_h_controlpoints_real.csv")


line_width = 0.8
cp_size = 60

# ---------- Plot 1: z, theta, w, q ----------
plt.figure(figsize=(10, 6))
plt.plot(times_z, values_z, marker=".", linestyle=":", linewidth=line_width, label="z")
plt.plot(times_theta, values_theta, marker=".", linestyle=":", linewidth=line_width, label="theta")
plt.plot(times_w, values_w, marker=".", linestyle=":", linewidth=line_width, label="w")
plt.plot(times_q, values_q, marker=".", linestyle=":", linewidth=line_width, label="q")

plt.scatter(cp_times_z, cp_values_z, s=cp_size, label="z control points")
plt.scatter(cp_times_theta, cp_values_theta, s=cp_size, label="theta control points")
plt.scatter(cp_times_w, cp_values_w, s=cp_size, label="w control points")
plt.scatter(cp_times_q, cp_values_q, s=cp_size, label="q control points")

plt.title("BeBOT states (real time): z, theta, w, q")
plt.xlabel("Time [s]")
plt.ylabel("Value")
plt.grid(True)
plt.legend()
plt.tight_layout()

# ---------- Plot 2: psi, r ----------
plt.figure(figsize=(10, 6))
plt.plot(times_psi, values_psi, marker=".", linestyle=":", linewidth=line_width, label="psi")
plt.plot(times_r, values_r, marker=".", linestyle=":", linewidth=line_width, label="r")

plt.scatter(cp_times_psi, cp_values_psi, s=cp_size, label="psi control points")
plt.scatter(cp_times_r, cp_values_r, s=cp_size, label="r control points")

plt.title("BeBOT states (real time): psi, r")
plt.xlabel("Time [s]")
plt.ylabel("Value")
plt.grid(True)
plt.legend()
plt.tight_layout()

# ---------- Plot 3: controls dv, dm, ds, dh ----------
plt.figure(figsize=(10, 6))
plt.plot(times_dv, values_dv, marker=".", linestyle=":", linewidth=line_width, label="delta_v")
plt.plot(times_dm, values_dm, marker=".", linestyle=":", linewidth=line_width, label="delta_m")
plt.plot(times_ds, values_ds, marker=".", linestyle=":", linewidth=line_width, label="delta_s")
plt.plot(times_dh, values_dh, marker=".", linestyle=":", linewidth=line_width, label="delta_h")

plt.scatter(cp_times_dv, cp_values_dv, s=cp_size, label="delta_v control points")
plt.scatter(cp_times_dm, cp_values_dm, s=cp_size, label="delta_m control points")
plt.scatter(cp_times_ds, cp_values_ds, s=cp_size, label="delta_s control points")
plt.scatter(cp_times_dh, cp_values_dh, s=cp_size, label="delta_h control points")

plt.title("BeBOT controls (real time): delta_v, delta_m, delta_s, delta_h")
plt.xlabel("Time [s]")
plt.ylabel("Value")
plt.grid(True)
plt.legend()
plt.tight_layout()

plt.show()

