import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

# ------------------------------------------------------------
# File generated by single_drone_receding_offline_test_obs
# ------------------------------------------------------------
csv_file = "mpc_15_step_extracted_states.csv"

# ------------------------------------------------------------
# Obstacles from your OCP
#   obs_x = [-0.6, 0.6]
#   obs_y = [ 2.0, 1.8]
#   obs_sep = 0.3
# ------------------------------------------------------------
obstacles = [
    {"x": -0.6, "y": 2.0, "radius": 0.3},
    {"x":  0.6, "y": 1.8, "radius": 0.3},
]

# ------------------------------------------------------------
# Load CSV
# ------------------------------------------------------------
df = pd.read_csv(csv_file)

required_columns = ["iteration", "initial_px", "initial_py"]

for col in required_columns:
    if col not in df.columns:
        raise ValueError(f"Missing required column in CSV: {col}")

# ------------------------------------------------------------
# Plot initial x-y points from every MPC iteration
# ------------------------------------------------------------
fig, ax = plt.subplots(figsize=(8, 6))

ax.plot(
    df["initial_px"],
    df["initial_py"],
    marker="o",
    linewidth=2,
    label="MPC initial states"
)

# Label each MPC point with iteration number
for _, row in df.iterrows():
    ax.text(
        row["initial_px"],
        row["initial_py"],
        str(int(row["iteration"])),
        fontsize=8,
        ha="right",
        va="bottom"
    )

# ------------------------------------------------------------
# Plot obstacles as safety circles
# ------------------------------------------------------------
for i, obs in enumerate(obstacles, start=1):
    circle = Circle(
        (obs["x"], obs["y"]),
        obs["radius"],
        fill=False,
        linewidth=2,
        label=f"Obstacle {i}, r={obs['radius']}"
    )
    ax.add_patch(circle)

    ax.plot(obs["x"], obs["y"], marker="x", markersize=10)

    ax.text(
        obs["x"],
        obs["y"],
        f"obs {i}",
        fontsize=9,
        ha="left",
        va="bottom"
    )

# Optional: mark start and target
ax.plot(-1.2, 1.8, marker="s", markersize=8, label="Start")
ax.plot( 1.2, 1.8, marker="*", markersize=12, label="Target")

# ------------------------------------------------------------
# Formatting
# ------------------------------------------------------------
ax.set_title("MPC initial states in XY plane with obstacles")
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.grid(True)
ax.axis("equal")
ax.legend()
plt.tight_layout()

# Save and show
plt.savefig("mpc_xy_initial_states_with_obstacles.png", dpi=300)
plt.show()
